name: Build OSC Relay Client (Auto)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate macOS spec file
      run: |
        pyi-makespec --name OSC_Relay_Client_mac --windowed --onefile --add-data "templates:templates" osc_relay_client.py
        
    - name: Build macOS app
      run: |
        pyinstaller OSC_Relay_Client_mac.spec
        
    - name: Create macOS zip
      run: |
        cd dist
        zip -r OSC_Relay_Client_macOS.zip OSC_Relay_Client_mac.app/
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: OSC-Relay-Client-macOS
        path: dist/OSC_Relay_Client_macOS.zip
        if-no-files-found: error
        
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate Windows spec file
      run: |
        pyi-makespec --name OSC_Relay_Client --windowed --onefile --add-data "templates;templates" osc_relay_client.py
        
    - name: Build Windows executable
      run: |
        pyinstaller OSC_Relay_Client.spec
        
    - name: Create Windows zip
      run: |
        cd dist
        powershell Compress-Archive -Path OSC_Relay_Client.exe -DestinationPath OSC_Relay_Client_Windows.zip -Force
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: OSC-Relay-Client-Windows
        path: dist/OSC_Relay_Client_Windows.zip
        if-no-files-found: error 