name: Build OSC Relay Client

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  actions: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build macOS app
      run: |
        pyinstaller OSC_Relay_Client_mac.spec
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: OSC-Relay-Client-macOS
        path: dist/OSC_Relay_Client.app/
        if-no-files-found: error
        
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Windows executable
      run: |
        pyinstaller OSC_Relay_Client.spec
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: OSC-Relay-Client-Windows
        path: dist/OSC_Relay_Client/
        if-no-files-found: error 