name: Build and Release (Auto)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# Add permissions configuration
permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate macOS spec file
      run: |
        pyi-makespec --name OSC_Relay_Client_mac --windowed --onefile --add-data "templates:templates" osc_relay_client.py
        
    - name: Build macOS app
      run: |
        pyinstaller OSC_Relay_Client_mac.spec
        
    - name: Create macOS zip
      run: |
        cd dist
        zip -r OSC_Relay_Client_macOS.zip OSC_Relay_Client_mac.app/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/OSC_Relay_Client_macOS.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate Windows spec file
      run: |
        pyi-makespec --name OSC_Relay_Client --windowed --onefile --add-data "templates;templates" osc_relay_client.py
        
    - name: Build Windows executable
      run: |
        pyinstaller OSC_Relay_Client.spec
        
    - name: Create Windows zip
      run: |
        cd dist
        powershell Compress-Archive -Path OSC_Relay_Client.exe -DestinationPath OSC_Relay_Client_Windows.zip -Force
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/OSC_Relay_Client_Windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 