name: Build and Release (Auto)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# Add permissions configuration
permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate macOS spec file
      run: |
        pyi-makespec --name OSC_Relay_Client_mac --windowed --onefile --add-data "templates:templates" osc_relay_client.py
        
    - name: Build macOS app
      run: |
        pyinstaller OSC_Relay_Client_mac.spec
        
    - name: Create macOS zip
      run: |
        cd dist
        zip -r OSC_Relay_Client_macOS.zip OSC_Relay_Client_mac.app/
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: OSC_Relay_Client_macOS
        path: dist/OSC_Relay_Client_macOS.zip
        
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate Windows spec file
      run: |
        pyi-makespec --name OSC_Relay_Client --windowed --onefile --add-data "templates;templates" osc_relay_client.py
        
    - name: Build Windows executable
      run: |
        pyinstaller OSC_Relay_Client.spec
        
    - name: Create Windows zip
      run: |
        cd dist
        powershell Compress-Archive -Path OSC_Relay_Client.exe -DestinationPath OSC_Relay_Client_Windows.zip -Force
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: OSC_Relay_Client_Windows
        path: dist/OSC_Relay_Client_Windows.zip
        
  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/OSC_Relay_Client_macOS/OSC_Relay_Client_macOS.zip
        asset_name: OSC_Relay_Client_macOS.zip
        asset_content_type: application/zip
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/OSC_Relay_Client_Windows/OSC_Relay_Client_Windows.zip
        asset_name: OSC_Relay_Client_Windows.zip
        asset_content_type: application/zip 